from .get_commission import CommissionAPI
from .send_to_qiwi import SendQIWIAPI
from .convert_currency import ConvertCurrencyAPI
from .currency_rates import CurrencyRatesAPI
from .cellular_payment import CellularPaymentAPI
from .transfer_card import TransferCardAPI
from .other_payments import OtherPaymentsAPI
from .free_payments import FreePaymentsAPI
from .detect_card import DetectCardAPI
from .detect_mobile import DetectMobileAPI
from .detect_provider import DetectProviderAPI
